name: Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-commit-message:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2-beta

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm i --only=dev

      - name: Add dependencies for commitlint action
        run: echo "::set-env name=NODE_PATH::$GITHUB_WORKSPACE/node_modules"

      - name: Lint Commit Messages
        uses: wagoid/commitlint-github-action@v1

  test-tsd:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2-beta

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i --only=dev

      - name: Test TypeScript definitions
        run: npm run test:tsd

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node: # https://nodejs.org/en/about/releases/
          - '*' # Current
          - '12' # Active LTS
          - '10' # Maintenance LTS
      fail-fast: false

    steps:
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i

      - name: Test (tsd)
        run: npm run test:tsd

      - name: Allow sudoless tcpdump
        run: |
          sudo groupadd pcap
          sudo usermod -a -G pcap $USER
          sudo chgrp pcap /usr/sbin/tcpdump
          sudo setcap cap_net_raw,cap_net_admin=eip /usr/sbin/tcpdump
          sudo ln -s /usr/sbin/tcpdump /usr/bin/tcpdump

      - name: Test (run) + Coverage
        run: npm run coverage:test

      - name: Coverage report
        continue-on-error: true
        run: npm run coverage:report

      - name: Coverage Upload
        continue-on-error: true
        if: ${{ success() }}
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.lcov

  release:
    runs-on: ubuntu-latest
    needs:
      - test
    if: ${{ success() && github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository == 'hertzg/node-net-keepalive' }}
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2-beta

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i --only=dev

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run release
